### PR TITLE
Dialog on branch switch

### PR DESCRIPTION
**Pull request by nvdweem**
I work on a laptop and I don't close my IDE when I stop working, however, I do switch branches when I switch tasks. When the plugin only shows the dialog on closing the IDE it doesn't help me much, so I added a feature that allows showing the dialog when the branch is switched.

Also, I noticed that the plugin is not compatible with the current EAP even though the comments seem to indicate that there should not be an untilVersion. I changed the gradle config to actually not include an untilVersion.

### CODE REVIEW

**Comment by nvdweem** [comment]
Not sure what is failing in the checks. The plugin seems to check agains Idea 2022.2+ versions which should run using Java 17, but the `Access to unresolved class java.lang.Record` errors indicate that they arent running Java 17.

If needed I can remove the `record` usage, but since Java 17 is used for Idea now it should be allowed to use it.

**Comment by nvdweem** [comment]
Not entirely sure, but I'm expecting this issue to come from:
https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/blob/master/Dockerfile
`FROM adoptopenjdk/openjdk11:alpine-slim`

**Comment by ChrisCarini** [comment]
Hi @nvdweem - First off, thank you for your contribution! I suspect this is also something I'd be interested in, but I'd like to learn more (see below).

For the workflow failure, please try syncing your fork and trying again. I am able to get the plugin verifier gradle task to pass locally once doing so (whereas I was not able to locally with just your branch/fork alone).

I will need a few days before I am able to test out this feature, but it'd be great to include some screenshots / manual testing steps (with a small test / public project, for example) so it's easier for folks to see exactly what this feature brings.

**Comment by nvdweem** [comment]
I merged your main into my fork. I'm on my work laptop now so I don't have the adjustments to the build.gradle that make the build work (there are some dependencies on secret-properties and there is no description on how to easily deal with that).
I'm pretty sure that I was able to run the pluginVerifierTask successfully before.
Like I mentioned in my previous message, the error that is given in the workflow is about `java.lang.Record` not being resolved, that's a Java version issue.
If it still doesn't work and you don't want to make the verifier run Java17 I'm also able to turn the record into a class, that should make the code compatible with Java11.

For the screenshots:
Branch Switch
Essentially:
- Have a branch open with unpushed commits
- Switch to a different branch
  - There should be a popup telling you about unpushed changes and asking to push
  - Continue without push will just switch the branch
  - Push opens the push dialog

From what I could tell, the listener doesn't allow preventing the branch switch so having a 'Cancel branch switch' button wasn't possible.

**Comment by ChrisCarini** [comment]
Hi @nvdweem - sorry for the delay.

This change looks great to me - I've confirmed this feature works as expected locally, and CI was failing because of the Dockerfile base image version as you said. I made a few small tweaks, and will get this feature released when I release the next version of this plugin (which, I intend to bump to 2022.3), so stay tuned!

Again, thank you for your contribution and this feature!

**Comment by nvdweem** [comment]
You are welcome, and thanks for including it in the next version :).

**Comment by ChrisCarini** [comment]
Absolutely! Don't forget to leave a review on [the plugin's JB marketplace page](https://plugins.jetbrains.com/plugin/19508-git-push-reminder), if you haven't already! ;)

**Comment by ChrisCarini** [comment]
@all-contributors please add @nvdweem for code, ideas

**Pull request merged**
